### ISSUE TITLE
TaskView 

### ISSUE THREAD

**Issue by Nattaro13** [cs2103jan2016-f14-4j/main#218]
- decide whether or not "name:" goes in

**Comment by dq-dx** [comment]
Maybe we could replace "Name:" with the task type i.e. "General:" / "Deadline:" / "Event:" ? This would help inform users what the icons mean as well.

Btw, should the compareTaskNames method in Task use compareToIgnoreCase instead of just compareTo? Because tasks with names that begin with smaller case will always be ranked below those that begin with upper case. This can happen when editing task names, which does auto capitalise.

```
add zzz
add aaa
1. Aaa
2. Zzz

set 1 "aaa"
1. Zzz
2. aaa
```
